// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNZrLeCfN8TJrBjs7XnI17lEbrJSyHx4g',
    appId: '1:157328186942:web:f0d5d8f3089fd8d5657b6f',
    messagingSenderId: '157328186942',
    projectId: 'freely-3ae6f',
    authDomain: 'freely-3ae6f.firebaseapp.com',
    storageBucket: 'freely-3ae6f.firebasestorage.app',
    measurementId: 'G-EZFWCDHHYG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvYuWqwocLoSFz04Wm-U1_IeErEFu4Imc',
    appId: '1:157328186942:android:ac4bfebc350b8a22657b6f',
    messagingSenderId: '157328186942',
    projectId: 'freely-3ae6f',
    storageBucket: 'freely-3ae6f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSmcMMUYl19kakOd2bg1Np-S0-C2ntOr0',
    appId: '1:157328186942:ios:51e6e9a8a4cdbc0b657b6f',
    messagingSenderId: '157328186942',
    projectId: 'freely-3ae6f',
    storageBucket: 'freely-3ae6f.firebasestorage.app',
    iosBundleId: 'com.example.freely',
  );
}
